"""create_price_listings_table

Revision ID: 83180cf78a1c
Revises: 0001_create_phone_tables
Create Date: 2026-05-21 09:36:10.994665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83180cf78a1c'
down_revision: Union[str, None] = '0001_create_phone_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('seller_name', sa.String(length=200), nullable=False),
    sa.Column('seller_rating', sa.Float(), nullable=True),
    sa.Column('seller_reviews_count', sa.Integer(), nullable=True),
    sa.Column('listed_price', sa.Integer(), nullable=False),
    sa.Column('coupon_discount', sa.Integer(), nullable=False),
    sa.Column('bank_discount', sa.Integer(), nullable=False),
    sa.Column('exchange_bonus', sa.Integer(), nullable=False),
    sa.Column('delivery_charge', sa.Integer(), nullable=False),
    sa.Column('final_price', sa.Integer(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('delivery_eta_days', sa.Integer(), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_listings')
    # ### end Alembic commands ###
