"""add_variants_and_pricing

Revision ID: edeaa1700b44
Revises: 29324cab9635
Create Date: 2026-05-22 23:40:21.853584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edeaa1700b44'
down_revision: Union[str, None] = '29324cab9635'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_id', sa.UUID(), nullable=False),
    sa.Column('ram_gb', sa.Integer(), nullable=False),
    sa.Column('storage_gb', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('sku_code', sa.String(length=100), nullable=True),
    sa.Column('slug', sa.String(length=250), nullable=False),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phone_variants_phone_id'), 'phone_variants', ['phone_id'], unique=False)
    op.create_index(op.f('ix_phone_variants_slug'), 'phone_variants', ['slug'], unique=True)
    op.create_table('variant_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('seller_name', sa.String(length=200), nullable=False),
    sa.Column('seller_rating', sa.Float(), nullable=True),
    sa.Column('seller_reviews_count', sa.Integer(), nullable=True),
    sa.Column('listed_price', sa.Integer(), nullable=False),
    sa.Column('original_mrp', sa.Integer(), nullable=True),
    sa.Column('coupon_discount', sa.Integer(), nullable=False),
    sa.Column('bank_discount', sa.Integer(), nullable=False),
    sa.Column('exchange_bonus', sa.Integer(), nullable=False),
    sa.Column('cashback_amount', sa.Integer(), nullable=False),
    sa.Column('delivery_charge', sa.Integer(), nullable=False),
    sa.Column('final_price', sa.Integer(), nullable=False),
    sa.Column('in_stock', sa.Boolean(), nullable=False),
    sa.Column('delivery_eta_days', sa.Integer(), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=False),
    sa.Column('emi_available', sa.Boolean(), nullable=False),
    sa.Column('emi_months', sa.Integer(), nullable=True),
    sa.Column('fake_discount_flag', sa.Boolean(), nullable=False),
    sa.Column('discount_authenticity_score', sa.Integer(), nullable=False),
    sa.Column('price_intelligence_note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['phone_variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_prices_variant_id'), 'variant_prices', ['variant_id'], unique=False)
    op.add_column('phone_specs', sa.Column('raw_colors', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_specs', 'raw_colors')
    op.drop_index(op.f('ix_variant_prices_variant_id'), table_name='variant_prices')
    op.drop_table('variant_prices')
    op.drop_index(op.f('ix_phone_variants_slug'), table_name='phone_variants')
    op.drop_index(op.f('ix_phone_variants_phone_id'), table_name='phone_variants')
    op.drop_table('phone_variants')
    # ### end Alembic commands ###
