"""create phone_interpretations table

Revision ID: ee3c91007b14
Revises: 5f892f5e313a
Create Date: 2026-05-22 20:37:44.076136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee3c91007b14'
down_revision: Union[str, None] = '5f892f5e313a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phone_interpretations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_id', sa.UUID(), nullable=False),
    sa.Column('battery_summary', sa.Text(), nullable=True),
    sa.Column('normal_usage', sa.String(length=100), nullable=True),
    sa.Column('heavy_usage', sa.String(length=100), nullable=True),
    sa.Column('charging_summary', sa.Text(), nullable=True),
    sa.Column('performance_summary', sa.Text(), nullable=True),
    sa.Column('display_summary', sa.Text(), nullable=True),
    sa.Column('camera_summary', sa.Text(), nullable=True),
    sa.Column('pros', sa.JSON(), nullable=True),
    sa.Column('cons', sa.JSON(), nullable=True),
    sa.Column('verdict', sa.Text(), nullable=True),
    sa.Column('expected_experience', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['phone_id'], ['phones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phone_interpretations')
    # ### end Alembic commands ###
